#! /bin/sh

# make this file executable first: sudo chmod 755 executeUponPiLogin
## This is file is executed upon rasperry booting

python /home/pi/BioMaker/GitHubGardenObserver/camera.py
sudo python /home/pi/BioMaker/GitHubGardenObserver/readAndStoreSensorData.py
cd BioMaker/GitHubGardenObserver/
./uploadToGitHub

countdownToShutDown=30
echo "WARNING: Pi will shut off in $countdownToShutDown sec. Press Ctrl-c to stop"

while  [$countdownToShutDown -le 1]
do
	echo $countdownToShutDown
	countdownToShutDown=$((countdownToShutDown-1))
done
sudo shutdown -h now

