#!/bin/bash
# My first script

# chmod 755 firstAttempt
echo "Hello World!"


# Run: ./firstAttempt
# If file is in a folder included in the path it can also be executed by $ firstAttempt

while 2>>1
do
	echo "Hello"
	sleep 3
done
echo "Ende"